version: '3.8'

services:
  intershop-app-pr:
    image: 'intershop-app-pr:latest'
    build:
      context: ./intershop
    container_name: intershop-app-pr
    depends_on:
      - db-intershop-pr
      - redis-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db-intershop-pr:5432/intershop
      - SPRING_R2DBC_USERNAME=someUser
      - SPRING_R2DBC_PASSWORD=d1ff1cultPasSw0rD
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db-intershop-pr:5432/intershop
      - SPRING_LIQUIBASE_USER=someUser
      - SPRING_LIQUIBASE_PASSWORD=d1ff1cultPasSw0rD
      - SPRING_DATA_REDIS_HOST=redis-server
      - PAYMENT_URL=http://payment-pr:8081
  payment-pr:
    image: 'payment-pr:latest'
    build:
      context: ./payment
    container_name: payment-pr
    depends_on:
      - db-intershop-pr
    ports:
      - "8081:8081"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db-intershop-pr:5432/intershop
      - SPRING_R2DBC_USERNAME=someUser
      - SPRING_R2DBC_PASSWORD=d1ff1cultPasSw0rD
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db-intershop-pr:5432/intershop
      - SPRING_LIQUIBASE_USER=someUser
      - SPRING_LIQUIBASE_PASSWORD=d1ff1cultPasSw0rD
  redis-server:
    image: redis:7.4.2-bookworm
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server"]
  db-intershop-pr:
    image: 'postgres:16-alpine'
    container_name: db-intershop-pr
    environment:
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: d1ff1cultPasSw0rD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: