db:
  schema-name: intershop
spring:
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myblog
    username: user
    password: pass
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ${db.schema-name}
        format_sql: true
        query.fail_on_pagination_over_collection_fetch: true
        jdbc.time_zone: UTC
        show_sql: false
    open-in-view: false
  liquibase:
    liquibase-schema: ${db.schema-name}
    default-schema: ${db.schema-name}
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: intershop